# Change to posgresql

default: &default
  adapter: postgresql
  encoding: utf8
  username: abraham
  password: <%= ENV['PROJECT_DATABASE_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: dotester_development

test:
  <<: *default
  database: dotester_test

production:
  <<: *default
  database: dotester_production
  username: username
  password: <%= ENV['PROJECT_DATABASE_PASSWORD'] %>
